spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/salex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: test
        jdbc:
          batch_size: 100
  graphql:
    graphiql:
      enabled: true
      path: /graphiql